# alacritty.toml
live_config_reload = true

[env]
TERM = "alacritty"

[window]
decorations     = "none"
dynamic_padding = false
dynamic_title   = true
opacity         = 0.84

[window.dimensions]
columns = 0
lines   = 0

[window.padding]
x = 0
y = 0

[scrolling]
history = 100000

# ============================================================================================
# "JetBrains Mono Fallback" is a custom font with fallbacks.
# create a conf file at "~/.config/fontconfig/conf.d/99-alias-fonts.conf".

# <?xml version="1.0"?>
# <!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
# <fontconfig>
#   <alias>
#     <family>JetBrains Mono Fallback</family>
#     <prefer>
#       <family>JetBrains Mono Medium</family>
#       <family>Symbols Nerd Font</family>
#       <family>Noto Color Emoji</family>
#     </prefer>
#   </alias>
# </fontconfig>
# ============================================================================================

[font.normal]
family = "JetBrains Mono Fallback"
style  = "Regular"

[font.bold]
family = "JetBrains Mono Fallback"
style  = "Bold"

[font.bold_italic]
family = "JetBrains Mono Fallback"
style  = "Bold Italic"

[font.italic]
family = "JetBrains Mono Fallback"
style  = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = -2

[font]
builtin_box_drawing = true
size                = 10

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.bright]
black=   "#928374"
red=     "#fb4934"
green=   "#b8bb26"
yellow=  "#fabd2f"
blue=    "#83a598"
magenta= "#d3869b"
cyan=    "#8ec07c"
white=   "#ebdbb2"

[colors.cursor]
cursor = "CellForeground"
text   = "CellBackground"

[colors.footer_bar]
background = "#C0C5CE"
foreground = "#232323"

[colors.hints.end]
background = "CellBackground"
foreground = "CellForeground"

[colors.hints.start]
background = "CellBackground"
foreground = "CellForeground"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black=   "#282828"
red=     "#cc241d"
green=   "#98971a"
yellow=  "#d79921"
blue=    "#458588"
magenta= "#b16286"
cyan=    "#689d6a"
white=   "#a89984"

[colors]
draw_bold_text_with_bright_colors = true

[colors.search.focused_match]
background = "CellBackground"
foreground = "CellForeground"

[colors.search.matches]
background = "CellBackground"
foreground = "CellForeground"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text   = "CellBackground"

[bell]
animation = "EaseOutExpo"
color     = "#C0C5CE"
command   = "None"
duration  = 0

[selection]
save_to_clipboard     = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
unfocused_hollow = true
vi_mode_style    = "None"

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Shift"

[mouse]
hide_when_typing = true

[debug]
highlight_damage   = false
log_level          = "Warn"
persistent_logging = false
print_events       = false
render_timer       = false
