theme = "darcula"

[editor]
scrolloff = 999
cursorline = true
line-number = "relative"
true-color = true
auto-format = false
popup-border = "all"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = true

[editor.indent-guides]
character = "│"
render = false
skip-levels = 1


[editor.lsp]
display-messages = true

[editor.statusline]
left = ["file-name", "file-modification-indicator"]
right = ["spinner", "position", "file-type"]

[keys.normal]
"C-q" = ":bc"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-k" = "jump_view_up"
"C-j" = "jump_view_down"
"C-tab" = "goto_next_buffer"
"C-S-tab" = "goto_previous_buffer"
"S-k" = "hover"
";" = ["insert_at_line_start", "normal_mode"]
"S-v" = ["extend_line_below","select_mode"]
"esc" = "keep_primary_selection"
"$" = "extend_to_line_end"
"0" = "goto_line_start"
"g" = { c = "toggle_comments" }
"G" = "goto_last_line"
"d" = { d = ["extend_to_line_bounds", "delete_selection"] }
"C-c" = ["extend_line_below", "select_mode", ":clipboard-yank-join"]
"C-S-v" = ":clipboard-paste-after"

[keys.insert]
"C-space" = "completion"

[keys.select]
"esc" = ["collapse_selection", "normal_mode", "keep_primary_selection"]
"g" = { c = "toggle_comments" }

[keys.normal.space]
"space" = "buffer_picker"
"s" = {f = "file_picker_in_current_directory"}
"t" = [":pipe-to alacritty", ":reload", ":redraw"]
# "5" = [":pipe-to zig build run > /tmp/log.txt 2>&1 & alacritty -e tail -f /tmp/log.txt", ":o /tmp/log.txt", ":reload", ":redraw"]
"5" = [":pipe-to zig build run > /tmp/log.txt 2>&1 & alacritty -e tail -f /tmp/log.txt", ":reload", ":redraw"]
